---
- name: Configure EC2 Security Groups
  hosts: localhost
  vars_files:
    - ../vars/ec2_vars.yml
    - ../vars/nectar_security_groups.yml
  tasks:
    - name: Configure EC2 Security Groups
      ec2_group:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        region: "{{ ec2_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        rules: "{{ item.rules }}"
        tags: { Name: "{{ item.name }}", Project: "{{ ec2_tag_project }}", Owner: "{{ ec2_tag_owner }}" }
        state: present
      with_items: "{{ security_groups }}"
